# Generated by Django 2.0 on 2018-03-17 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ask_film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='film demandé')),
                ('langage', models.CharField(max_length=50, verbose_name='langage')),
                ('soustitre', models.CharField(max_length=50, verbose_name='sous-titre')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ask_jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='jeu demandé.')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ask_livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='livre demandé.')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ask_logiciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='logiciel demandé.')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ask_musique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='musique demandée.')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ask_serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='serie demandé')),
                ('langage', models.CharField(max_length=50, verbose_name='langage')),
                ('soustitre', models.CharField(max_length=50, verbose_name='sous-titre')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='titre')),
                ('annee', models.IntegerField(verbose_name='année')),
                ('Genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('realisateur', models.CharField(max_length=40, verbose_name='réalisateur')),
                ('qualite', models.CharField(max_length=20, verbose_name='qualité')),
                ('langage', models.CharField(max_length=40, verbose_name='Langage')),
                ('soustitre', models.CharField(max_length=40, verbose_name='Langage sous-titres')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='films/images/')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('fichier', models.FileField(upload_to='films/fichiers/', verbose_name='Fichier ( max : 50Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'films',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='jeux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('annee', models.IntegerField(verbose_name='Année de sortie')),
                ('edition', models.CharField(max_length=40, verbose_name='entreprise')),
                ('langage', models.CharField(max_length=40, verbose_name='Langage')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='jeux/images/')),
                ('presentation', models.TextField(verbose_name='Présentation')),
                ('crack', models.TextField(null=True, verbose_name='Méthode de crackage')),
                ('fichier', models.FileField(upload_to='jeux/fichiers/', verbose_name='Fichier ( max : 100Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeux',
                'ordering': ['nom', 'version'],
            },
        ),
        migrations.CreateModel(
            name='livres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=50, verbose_name='Auteur')),
                ('annee', models.IntegerField(verbose_name='Année de sortie')),
                ('langage', models.CharField(max_length=30, verbose_name='Langage')),
                ('Genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='livres/images/')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('fichier', models.FileField(upload_to='livres/fichiers/', verbose_name='Fichier ( max : 2Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'livres',
                'ordering': ['nom', 'auteur'],
            },
        ),
        migrations.CreateModel(
            name='logiciels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('version', models.CharField(max_length=20, verbose_name='Version logiciel')),
                ('annee', models.IntegerField(verbose_name='Année de sortie')),
                ('license', models.CharField(max_length=20, verbose_name='License')),
                ('langage', models.CharField(max_length=30, verbose_name='Langage')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='logiciels/images/')),
                ('presentation', models.TextField(verbose_name='Présentation')),
                ('crack', models.TextField(null=True, verbose_name='Méthode de crackage')),
                ('fichier', models.FileField(upload_to='logiciels/fichiers/', verbose_name='Fichier ( max : 100Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'logiciels',
                'ordering': ['nom', 'version'],
            },
        ),
        migrations.CreateModel(
            name='musiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=50, verbose_name='Artiste')),
                ('titre', models.CharField(max_length=50, verbose_name='Titre album')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('Genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('qualite', models.CharField(max_length=20, verbose_name='Qualité')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='musiques/images/')),
                ('synopsis', models.TextField(verbose_name='Présentation')),
                ('tracklist', models.TextField(verbose_name='Liste des pistes audios')),
                ('fichier', models.FileField(upload_to='musiques/fichiers/', verbose_name='Fichier ( max : 2Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'musiques',
                'ordering': ['artiste', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='titre')),
                ('annee', models.IntegerField(verbose_name='année de production')),
                ('nbepisodes', models.IntegerField(verbose_name="nombre d'épisodes")),
                ('Genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('plateforme', models.CharField(max_length=30, verbose_name='Entreprise de production')),
                ('qualite', models.CharField(max_length=20, verbose_name='Qualité')),
                ('langage', models.CharField(max_length=40, verbose_name='Langage')),
                ('soustitre', models.CharField(max_length=40, verbose_name='Language sous-titres')),
                ('nbTelechargement', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='series/images/', verbose_name='Jaquette/ Image')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('fichier', models.FileField(upload_to='series/fichiers/', verbose_name='Fichier ( max : 100Go )')),
                ('datedepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mise en ligne')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'series',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='userprofil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.TextField(choices=[('1A', '1ère année'), ('2A', '2ème année'), ('3A', '3ème année')], default='1A')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
